
data _hrtdis replace;
	infile "C:\Users\arobe\OneDrive\Documents\SAS_Data\hw2_data.csv" dlm=',' firstobs=2 n=5;
	input Y $ X1 X2 $ X3 $ X4 $;
	run;
proc print data= _hrtdis;
run;
data hrtdis;
	set _hrtdis;
		if Y='0.00' then Y='No Disease';
		if Y='1.00' then Y='Disease';
		if X2='0.00' then X2='Not Hypertensive';
		if X2='1.00' then X2='Hypertensive';
		if X3='0.00' then X3='Female';
		if X3='1.00' then X3='Male';
		if X4='2.00' then X4="Not Obese";
		if X4='1.00' then X4="Obese";
	run;
proc freq data=_hrtdis;
	Tables X2/cellchi2 chisq;
	Tables X3/cellchi2 chisq;
	Tables Y*X1/chisq;
	Tables X3*X2*Y/CMH;
	run;
proc logistic data=_hrtdis descending;
	model Y= X1 X2 X3 X4 / lackfit;
run;
proc logistic data=_hrtdis descending;
	class X2 X3 X4;
	model Y= X1 X2 X3 X4 / lackfit;
	units X1=1;
run;
