*input datafile and variables;
*Y = Hours Worked;
data df;
	infile "C:\Users\arobe\OneDrive\Documents\SAS_Data\DataHomework3.csv" dlm=',';
	input Y X1 X2 X3 X4 X5 X6 X7 X8;
run;
*create dummy variables for X8 where X8=3 is the reference;
*These variables will be used "in place of" X8;
data df;
  set df;
  if X8 = '2' then D1 = 1;
  else D1 = 0;
  if X8 = '1' then D2 = 1;
  else D2 = 0;
run;
* Run linear regression with selected variables (X8 is now D1 and D2);
proc reg data=df;
	model Y = X1 X2 X3 D1 D2;
run;
* Run a parial correlation procedure for Y and X3 while controlling for X2;
proc corr data=df;
	var Y X3;
	partial X2;
run;
* Create a correlation matrix with all variables;
proc corr data=df;
	var Y X1 X2 X3 X4 X5 X6 X7 D1 D2;
run;
* Run a stepwise procedure to select the best predictors for a model;
proc stepwise data=df;
	model Y = X1 X2 X3 X4 X5 X6 X7 D1 D2;
run;
