data _hrtdis;
	infile "C:\Users\arobe\OneDrive\Documents\SAS_Data\hw2_data.csv" dlm=',' firstobs=2 n=5;
	input Y X1 X2 X3 X4;
		if X4=2.00 then X4=0.00;
	run;
proc means data= _hrtdis;
	var X1;
run;
proc freq data=_hrtdis;
	Tables X2/cellchi2 chisq;
	Tables X3/cellchi2 chisq;
	Tables Y*X1/chisq;
	Tables X3*X2*Y/CMH;
	Tables Y*(X1 X2 X3 X4) / expected sparse;
	run;
proc print data=freqcount;
	run;
proc logistic descending;
	model Y= X1 / lackfit;
run;
proc logistic descending;
	model Y= X1 X2 X3 X4 / details lackfit;
run;
